theme: jekyll-theme-slate
# Site settings
title: 21年中国创新方法大赛比赛总结                     #你博客的标题
SEOTitle: 21年中国创新方法大赛比赛总结       #显示在浏览器上搜索的时候显示的标题
header-img: 333.png    #显示在首页的背景图片
email: k359579923@gmail.com   
description: ""              #网站介绍
keyword: "比赛" #关键词
url: "https://mabotian.github.io/"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
